#!/bin/sh
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=28b8dea680e154fd275f8ee4d1081edad36cafe0
fi

files=$(git diff-index --cached --diff-filter=ACMRTUXB --name-only $against | grep "\.rb$")
if [[ -n $files ]]; then
    bundle exec rubocop $files
fi
